### ISSUE TITLE
Choose data base engine

### ISSUE THREAD

**Issue by buker** [TimeGladiator/TimeGladiator#2]
We need to choose a database engine to store data for the whole application.

Proposal:
1. Postgresql - easy to use, globaly known, we can host it every where
2. Scylla - hard, probably not needed

**Comment by michaelcmarafino** [comment]
My vote is for Postgres. Very popular in the industry so it would give some good experience if everyone had some time using it here.

**Comment by buker** [comment]
We could also here talk about lib. Do you want use Gorm, sqlx or sqlc. All has pros and cos. For me the most useless is Gorm

**Comment by indigowar** [comment]
> We could also here talk about lib. Do you want use Gorm, sqlx or sqlc. All has pros and cos. For me the most useless is Gorm

I would go with sqlc, because it generates such a nice boilerplate for queries, and it integrates with many migrations tools: https://docs.sqlc.dev/en/latest/howto/ddl.html.

**Comment by buker** [comment]
For now we will go with Postgresql and SQL
