### ISSUE TITLE
Chose http library

### ISSUE THREAD

**Issue by buker** [TimeGladiator/TimeGladiator#3]
We need to choose http library. and router.

1. Framework like gin, echo etc
2. Full stdlib
3. stdlib + chi router

**Comment by jemaltahir** [comment]
I would opt the approach with standard library net/http and Chi.

**Comment by minhnghia2k3** [comment]
Are there any advantages to using `stdlib with Chi` versus just using `stdlib`? As I know, the latest Go version has fully supports declaring HTTP methods
![image](https://github.com/user-attachments/assets/832d6cbb-b965-49fb-beb1-c97b8f2ab9a0)

**Comment by jemaltahir** [comment]
I think `stdlib` will do fine unless we are facing some complex routing.

**Comment by minhnghia2k3** [comment]
I haven't tried using Chi, but it's worth learning new things.

**Comment by buker** [comment]
Chi is compatible with standard lib. We can go fully standard lib and when needed replace it with Chi if we will missing something

**Comment by buker** [comment]
We are going with full standard lib, we will change it when needed.
